// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview A report improvement suggestion AI agent.
 *
 * - suggestReportImprovements - A function that suggests improvements for a given report.
 * - SuggestReportImprovementsInput - The input type for the suggestReportImprovements function.
 * - SuggestReportImprovementsOutput - The return type for the suggestReportImprovements function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestReportImprovementsInputSchema = z.object({
  report: z
    .string()
    .describe('The generated report content that needs improvement suggestions.'),
});
export type SuggestReportImprovementsInput = z.infer<
  typeof SuggestReportImprovementsInputSchema
>;

const SuggestReportImprovementsOutputSchema = z.object({
  suggestions: z
    .array(z.string())
    .describe('An array of improvement suggestions for the report.'),
});
export type SuggestReportImprovementsOutput = z.infer<
  typeof SuggestReportImprovementsOutputSchema
>;

export async function suggestReportImprovements(
  input: SuggestReportImprovementsInput
): Promise<SuggestReportImprovementsOutput> {
  return suggestReportImprovementsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestReportImprovementsPrompt',
  input: {schema: SuggestReportImprovementsInputSchema},
  output: {schema: SuggestReportImprovementsOutputSchema},
  prompt: `You are an AI assistant that helps improve reports. Review the provided report and suggest improvements to make it more comprehensive and insightful. Provide specific and actionable suggestions.

Report:
{{{report}}}`,
});

const suggestReportImprovementsFlow = ai.defineFlow(
  {
    name: 'suggestReportImprovementsFlow',
    inputSchema: SuggestReportImprovementsInputSchema,
    outputSchema: SuggestReportImprovementsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
